:description: This is an introduction to the Neo4j Data Importer Manual.
= Introduction

Neo4j Data Importer is a tool for importing data into Neo4j and is ideal to get started quickly with testing and prototyping.
It is UI-based and allows you to import data from flat files without using any code.
This means that you can import data from any source that can be exported to a flat file and does thus not require DBMS filesystem access.

Using Data Importer is only one way to import data into Neo4j and may not meet all import needs.
See xref:import-others.adoc[] for a full list of options.

Data Importer is currently available both as part of Neo4j Workspace and as a standalone product.
Workspace is available on Neo4j AuraDB instances, and Data Importer is accessed via the _Import_ tab.
Additionally, Workspace offers options to both query and visually explore your data, once it's imported.

The standalone version is accessible at link:https://data-importer.neo4j.io/[] using a secure connection.
Additionally, Data Importer standalone is also available at link:https://data-importer.graphapp.io/[] and link:http://data-importer.graphapp.io/[] with both secure and insecure connections.

[NOTE]
====
In general, it is recommended to always use a secure connection.
However, some web browsers have security constraints that require an unsecure connection.
====

Workspace offers interactive, in-product guides where you can get a hands-on learning experience with all three available tools, Import, Explore, and Query.

Many things covered in this document are also offered in the Import guide.
The guides can be accessed from the top right corner of the UI.

